# Generated by Django 2.2 on 2020-02-08 15:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('orden', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('mostrar_caja', models.BooleanField(blank=True, default=False, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('pagado', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('recargo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('tipo_fact', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('color', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('direccion', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('observaciones', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('id_tributario', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, default='', max_length=600, null=True)),
                ('imagen', models.ImageField(blank=True, default='', null=True, upload_to='images/')),
                ('orden', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('color', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cantidad_venta', models.IntegerField(blank=True, default=0, null=True)),
                ('coste', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('ultimo_movimiento', models.DateTimeField(auto_now=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('mostrar', models.BooleanField(blank=True, default=False, null=True)),
                ('codigo_barra', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_bodega', models.IntegerField(blank=True, default=0, null=True)),
                ('tipo_producto', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('estado_inv', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('multiplicador_hijos', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_cat', to='api.Categoria')),
                ('proveedor', models.ManyToManyField(related_name='productos_prv', to='api.Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_cambio', models.DateTimeField(auto_now=True)),
                ('cant_venta', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('desc_prod', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('recargo_prod', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=1000, null=True)),
                ('precio_real', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.Factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='facturados', to='api.Producto')),
            ],
            options={
                'unique_together': {('factura', 'producto')},
                'index_together': {('factura', 'producto')},
            },
        ),
    ]
