# Generated by Django 2.2 on 2020-02-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200208_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('UND', 'Unidad'), ('KG', 'Kilogramos'), ('GRS', 'Gramos'), ('LTS', 'Litros'), ('MLTS', 'Mili-Litros')], default='UND', max_length=4, null=True),
        ),
    ]
