# Generated by Django 2.2 on 2020-02-08 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200208_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='mostrar',
            new_name='mostrar_caja',
        ),
    ]
